NFL_APP/Pages/League/DivisionsAndConferences.cshtml.cs
using Data.Models;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NFL_APP.Pages.League
{
    public class DivisionsAndConferencesModel : PageModel
    {
        private readonly SqlTeamRepository repository;

        public IReadOnlyList<GetDivisionsAndConferences> Conferences { get; private set; } = new List<GetDivisionsAndConferences>();

        public DivisionsAndConferencesModel(SqlTeamRepository repository)
        {
            this.repository = repository;
        }

        public void OnGet()
        {
            Conferences = repository.RetrieveDivisionsAndConferences;
        }
    }
}

NFL_APP/Pages/League/League.cshtml.cs
using Data;
using Data.Models;
using DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NFL_APP.Pages.League
{
    public class LeagueModel : PageModel
    {

        private readonly SqlTeamRepository repository;

        // keep track of how many conference we have
        private static int _conferenceCount = 2;
        public int ConferenceCount { get => _conferenceCount; set { _conferenceCount = value; } }
        private static int _divisionCount = 8;
        public int DivisionCount { get => _divisionCount; set { _divisionCount = value; } }

        // To store the values for Creating a Team
        [BindProperty]
        public string? City { get; set; }

        [BindProperty]
        public string? State { get; set; }

        [BindProperty]
        public string? Name { get; set; }

        [BindProperty]
        public string? StadiumName { get; set; }

        [BindProperty]
        public int ConferenceID { get; set; }

        [BindProperty]
        public int DivisionID { get; set; }

        public LeagueModel(SqlTeamRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult OnPostCreateTeam()
        {
            if (string.IsNullOrWhiteSpace(City) || string.IsNullOrWhiteSpace(State) ||
                        string.IsNullOrWhiteSpace(Name) || string.IsNullOrWhiteSpace(StadiumName))
            {
                ModelState.AddModelError("", "All fields are required.");
                return Page();
            }

            try
            {
                repository.CreateTeam(DivisionID, ConferenceID, City, State, Name, StadiumName);


                City = string.Empty;
                State = string.Empty;
                Name = string.Empty;
                StadiumName = string.Empty;
                ConferenceID = 0;
                DivisionID = 0;

                return Page(); // Redirect to a success page after creation
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred: " + ex.Message);
                return Page();
            }
        }

        // Store values for creating a Conference
        [BindProperty]
        public string? CreateConferenceName { get; set; }

        public IActionResult OnPostCreateConference()
        {
            if (string.IsNullOrWhiteSpace(CreateConferenceName))
            {
                ModelState.AddModelError("", "All fields are required.");
                return Page();
            }

            try
            {
                repository.CreateConference(CreateConferenceName);
                ConferenceCount++;

                CreateConferenceName = string.Empty;

                return Page();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred: " + ex.Message);
                return Page();
            }
        }

        [BindProperty]
        public string? CreateDivisionName { get; set; }

        [BindProperty]
        public int CreateConferenceID { get; set; }

        public IActionResult OnPostCreateDivision()
        {
            if (string.IsNullOrWhiteSpace(CreateDivisionName))
            {
                ModelState.AddModelError("", "All fields are required.");
                return Page();
            }

            try
            {
                repository.CreateDivision(CreateDivisionName, CreateConferenceID);
                DivisionCount++;

                CreateDivisionName = string.Empty;
                CreateConferenceID = 0;

                return Page();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred: " + ex.Message);
                return Page();
            }
        }

        public void OnGet()
        {
        }
    }
}

NFL_APP/Pages/League/ViewTeams.cshtml.cs
using Data.Models;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NFL_APP.Pages.League
{
    public class ViewTeamsModel : PageModel
    {
        private readonly SqlTeamRepository repository;
        public string SelectedType { get; set; } = "All"; // Default

        public List<string> TableHeaders = new List<string> {"ConferenceSeeding", "IsConferenceChamp", "City", "State", "Name", "StadiumName"};

        public IReadOnlyList<ConferenceTeams> Teams { get; private set; } = new List<ConferenceTeams>();

        public ViewTeamsModel(SqlTeamRepository repository)
        {
            this.repository = repository;
        }

        public void OnGet()
        {
            // Default to QB on first load
            LoadTeams("All");
        }

        public IActionResult OnPostGetConference(string type)
        {
            SelectedType = type;
            LoadTeams(type);
            return Page();
        }

        private void LoadTeams(string position)
        {
            switch (position)
            {
                case "All":
                    Teams = repository.RetrieveAllTeams;
                    break;
                case "AFC":
                    Teams = repository.RetrieveAFCTeams;
                    break;
                case "NFC":
                    Teams = repository.RetrieveNFCTeams;
                    break;
            }
        }
    }
}

NFL_APP/Pages/League/DivisionsAndConferences.cshtml
@page
@model NFL_APP.Pages.League.DivisionsAndConferencesModel
@{
}
<!-- Page Header -->
<h1 class="text-center mb-4">Divisions (With Associated Conference)</h1>

<!-- Table -->
<div class="container">
    <table class="table table-bordered table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Division Name</th>
                <th>Conference</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var stat in Model.Conferences)
            {
                <tr>
                    <td>@stat.DivisionName</td>
                    <td>@stat.ConferenceName</td>
                </tr>
            }
        </tbody>
    </table>
</div>

NFL_APP/Pages/League/League.cshtml
@page
@model LeagueModel
@{
}


<div class="container mt-5">
    <h2 class="text-center mb-4">Commisioner Panel</h2>

    <div class="card mb-4 shadow-sm">
        <div class="card-header bg-primary text-white">Create a New Team</div>
        <div class="card-body">
            <!--create a team-->
            <form method="post" asp-page-handler="CreateTeam">
                <div class="row mb-3">
                    <div class="col">
                        <label asp-for="City" class="form-label"></label>
                        <input asp-for="City" class="form-control" />
                    </div>
                    <div class="col">
                        <label asp-for="State" class="form-label">State (example: CA, KS, MO)</label>
                        <input asp-for="State" class="form-control" maxlength="2" pattern="^[A-Z]{2}$" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label asp-for="Name" class="form-label"></label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <div class="col">
                        <label asp-for="StadiumName" class="form-label"></label>
                        <input asp-for="StadiumName" class="form-control" />
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label asp-for="ConferenceID" class="form-label"></label>
                        <input asp-for="ConferenceID" type="number" class="form-control" min="1" max="@Model.ConferenceCount" />
                    </div>
                    <div class="col">
                        <label asp-for="DivisionID" class="form-label"></label>
                        <input asp-for="DivisionID" type="number" class="form-control" min="1" max="@Model.DivisionCount" />
                    </div>
                </div>
                <button type="submit" class="btn btn-success" asp-page-handler="CreateTeam">Create Team</button>
            </form>

        </div>
    </div>
    <div class="card mb-4 shadow-sm">
        <div class="card-header bg-secondary text-white">Create a New Conference</div>
        <div class="card-body">
            <!--Create a conference-->
            <form method="post" asp-page-handler="CreateConference">
                <div class="mb-3">
                    <label class="form-label" for="ConferenceName">Conference Name</label>
                    <input id="ConferenceName" class="form-control" required asp-for="CreateConferenceName" />

                </div>
                <button type="submit" class="btn btn-success">Create Conference</button>
            </form>
        </div>
    </div>



    <div class="card shadow-sm">
        <div class="card-header bg-info text-white">Create a New Division</div>
        <div class="card-body">
            <!--create a divison-->
            <form method="post" asp-page-handler="CreateDivision">
                <div class="row mb-3">
                    <div class="col">
                        <label class="form-label">Division Name</label>
                        <input id="DivisionName" class="form-control" required asp-for="CreateDivisionName" />
                    </div>
                    <div class="col">
                        <div class="mb-3">
                            <label asp-for="CreateConferenceID" class="form-label"></label>
                            <input type="number" class="form-control" asp-for="CreateConferenceID" required min="1" max="@Model.ConferenceCount" />
                            <span asp-validation-for="CreateConferenceID" class="text-danger"></span>
                        </div>

                    </div>
                </div>
                <button type="submit" class="btn btn-success">Create Division</button>
            </form>
        </div>
    </div>
</div>
<div class="container mt-3">
    <a class="btn btn-primary" href="@Url.Page("/League/DivisionsAndConferences")">View Divisions and Conferences</a>
</div>

NFL_APP/Pages/League/ViewTeams.cshtml
@page
@model NFL_APP.Pages.League.ViewTeamsModel
@{
}
<h1 class="text-center mb-4">Team Rankings</h1>

<!--View the teams, AFC, ALL, NFC-->
<div class="text-center mb-4">
    <form method="post" asp-page-handler="GetConference" style="display:inline;">
        <input type="hidden" name="type" value="AFC" />
        <button type="submit" class="btn @(Model.SelectedType == "AFC" ? "btn-danger" : "btn-outline-danger")">AFC</button>
    </form>
    <form method="post" asp-page-handler="GetConference" style="display:inline;">
        <input type="hidden" name="type" value="All" />
        <button type="submit" class="btn @(Model.SelectedType == "All" ? "btn-secondary" : "btn-outline-secondary")">All</button>
    </form>
    <form method="post" asp-page-handler="GetConference" style="display:inline;">
        <input type="hidden" name="type" value="NFC" />
        <button type="submit" class="btn @(Model.SelectedType == "NFC" ? "btn-primary" : "btn-outline-primary")">NFC</button>
    </form>
</div>


<div id="statsTable">
    <table class="table table-bordered table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                @foreach (var header in Model.TableHeaders)
                {
                    <th>@header</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var stat in Model.Teams)
            {
                <tr>
                    <td>@stat.ConferenceSeeding</td>
                    <td>@stat.IsConferenceChamp</td>
                    <td>@stat.City</td>
                    <td>@stat.State</td>
                    <td>@stat.Name</td>
                    <td>@stat.StadiumName</td>
                </tr>
            }
        </tbody>
    </table>
</div>